steps:
# Build Go tools in a local image without publishing.
# Downstream images pull in these tools using an external image stage.
# https://docs.docker.com/develop/develop-images/multistage-build/#use-an-external-image-as-a-stage
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'tools-local',
    '.'
  ]
# Build target image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg',
    'argocd_version=${_ARGOCD_VERSION}',
    '--build-arg',
    'vault_version=${_VAULT_VERSION}',
    '-t',
    '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}-${COMMIT_SHA}',
    '-t',
    '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}-${SHORT_SHA}',
    '-t',
    '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}',
    './images/${_IMAGE}'
  ]
  timeout: 500s
images:
- '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}-${COMMIT_SHA}'
- '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}-${SHORT_SHA}'
- '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}'
tags: # These are CloudBuild tags, not docker image tags
- '${BRANCH_NAME}-${COMMIT_SHA}'
- '${BRANCH_NAME}-${SHORT_SHA}'
- '${BRANCH_NAME}'
substitutions:
  _REGISTRY_HOST: us-central1-docker.pkg.dev # Artifact Registry host
  _IMAGE: __UNDEFINED__ # Overriden by trigger. eg "argocd-custom-image", "jenkins-gke-deploy"
  _ARGOCD_VERSION: 1.7.7
  _VAULT_VERSION: 1.1.0
