name: Run Unit Tests
on:
  push:
    branches:
      - main
    paths:
      - 'tools/**'
  pull_request:
    branches:
      - main
    paths:
      - 'tools/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: run tests
        run: go test -v -coverprofile=cover.out -covermode=count ./...
        working-directory: ./tools
      - name: upload coverage
        uses: codecov/codecov-action@v1
        working-directory: ./tools
        with:
          files: ./cover.out
          flags: unittests
          fail_ci_if_error: true
